### ISSUE TITLE
checkmate incorrect

### ISSUE THREAD

**Issue by sonic597** [hvgupta/NewChesstrail#1]
![Screenshot 2023-02-25 at 2 08 30 PM](https://user-images.githubusercontent.com/30410081/221341687-eb9285da-9054-4319-a0ea-004bded79e19.png)
The king is unable to move, but the pawn killing queen is not considered

**Comment by sonic597** [comment]
white pawn defends white queen instigates error

**Comment by hvgupta** [comment]
the code was not properly checking pawn's attack, fixed it now.
